### ISSUE TITLE
Support Walls backsight format

### ISSUE THREAD

**Issue by jlillest** [jedwards1211/dewalls#3]
A standard walls format is similar to the following(ORDER=DAV):
```
#PREFIX SUPERCAVE
1	20	3.65	0	-90	<7,0,30,6>
20	21	16	340	2.5	<7,0,34,2>
```
But if we want to enter a backsight on one of the shots, we use a slash("/"):
```
1	20	3.65	/0	-90	<7,0,30,6>
```

For a foresight/backsight, we would do the following:
```
1	20	3.65	179/0	-90	<7,0,30,6>
```

I haven't checked to see if the latter is supported, but this is a feature request to support the former format.

Philip showed me the catch test stuff, and I'll work on getting some tests written and then see if I can get the code working.

**Comment by jedwards1211** [comment]
It supports things like `179/0` or `--/0` but I hadn't seen anything in the PDF docs about plain `/0` being supported.  You've gotten Walls to accept that huh?  I figure we will probably discover some undocumented features... :)

**Comment by jedwards1211** [comment]
Sure enough, you were right about this.  You didn't actually learn this from any documentation did you?  As far as I can tell it's not in any documentation
